-- V1: 초기 테이블 (docs/ERD.md 기준)
-- [배포 전 규칙] 아직 미배포 상태이므로 스키마 변경은 이 파일(V1)을 직접 수정한다.
--   수정 후에는 DB 초기화(docker compose down -v && up -d db)가 필요하다.
-- 배포 이후부터는 V2, V3... 새 마이그레이션 파일로만 변경한다.

create table account (
    id            bigint generated by default as identity primary key,
    username      varchar(255) not null,
    email         varchar(255),
    password_hash varchar(255) not null,
    role          varchar(255) not null
        constraint account_role_check
            check (role in ('ADMIN', 'STAFF', 'TRAINER', 'MEMBER')),
    created_at    timestamptz(6) not null,
    constraint uk_account_username unique (username)
);

create table member (
    id         bigint generated by default as identity primary key,
    account_id bigint,
    member_no  varchar(255) not null,
    name       varchar(255) not null,
    phone      varchar(255),
    gender     varchar(255),
    birth_date date,
    created_at timestamptz(6) not null,
    deleted_at timestamptz(6),
    constraint uk_member_member_no unique (member_no)
);

create table attendance (
    id            bigint generated by default as identity primary key,
    member_id     bigint not null
        constraint fk_attendance_member references member (id),
    checked_in_at timestamptz(6) not null
);

-- 날짜별 출석 현황 조회용 (메인 화면 핵심 쿼리)
create index idx_attendance_checked_in_at on attendance (checked_in_at);

-- 헬스 이용권 (docs/ERD.md §3.5). 회원 필드가 아닌 별도 테이블 — 여러 번 구매 가능(1:N)
create table membership (
    id         bigint generated by default as identity primary key,
    member_id  bigint not null
        constraint fk_membership_member references member (id),
    start_date date not null,
    end_date   date not null,
    status     varchar(255) not null
        constraint membership_status_check
            check (status in ('ACTIVE', 'EXPIRED')),
    created_at timestamptz(6) not null
);

-- 회원별 이용권 이력 조회용
create index idx_membership_member_id on membership (member_id);

-- PT권 (docs/ERD.md §3.6). 유효 기간 없음. total_count 는 부여 후 바뀌지 않고 remaining_count 만 움직인다.
-- 잔여 횟수가 음수가 되지 않는다는 규칙은 엔티티가 지키지만, 최종 방어선으로 DB 제약도 둔다.
create table pt_pass (
    id              bigint generated by default as identity primary key,
    member_id       bigint not null
        constraint fk_pt_pass_member references member (id),
    total_count     integer not null
        constraint pt_pass_total_count_check check (total_count >= 1),
    remaining_count integer not null
        constraint pt_pass_remaining_count_check check (remaining_count >= 0),
    created_at      timestamptz(6) not null
);

-- 회원별 PT권 목록·잔여 합계 조회용
create index idx_pt_pass_member_id on pt_pass (member_id);

-- PT 횟수 변동 이력 (docs/ERD.md §3.6.1). 추가만 한다 — 누가 언제 왜 바꿨는지의 근거
create table pt_pass_adjustment (
    id              bigint generated by default as identity primary key,
    pt_pass_id      bigint not null
        constraint fk_pt_pass_adjustment_pt_pass references pt_pass (id),
    type            varchar(255) not null
        constraint pt_pass_adjustment_type_check check (type in ('MANUAL')),
    delta           integer not null
        constraint pt_pass_adjustment_delta_check check (delta <> 0),
    remaining_after integer not null
        constraint pt_pass_adjustment_remaining_after_check check (remaining_after >= 0),
    reason          varchar(255) not null,
    adjusted_by     varchar(255) not null,
    created_at      timestamptz(6) not null
);

-- PT권별 변동 이력 조회용
create index idx_pt_pass_adjustment_pt_pass_id on pt_pass_adjustment (pt_pass_id);
